### ISSUE TITLE
Formular pro pridani rekordu

### ISSUE THREAD

**Issue by milkydan** [oarepo/publications-ui#38]
- [x] pri vyberu jazyka rekordu nefunguje strankovani jazyku (vidim jazyky od "Afarština" - "Asámština")
- [x]  narazil jsem na problem se zadavinim identifikatoru - obecne je to asi problem u kazdeho pole, pokud server provadi validaci a nejde se posunout na dalsi krok kvuli chybe toho co jsem vyplnil, chtelo by to, aby tam byly nejake hlasky, ze kterych uzivatel dekoduje proc nemuze dal, ted je tam popisek "Ve formulari se vyskytla chyba"

**Comment by mirekys** [comment]
Vsechny problemy by mely byt vyresene v #39
